# Generated by Django 3.0.7 on 2020-06-14 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.fields import ArrayField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('business_abbr', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('sales_revenue', models.FloatField(blank=True, null=True)),
                ('accounting_software', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(max_length=100, default="United States of America", blank=True, null=True)),
                ('countries_of_operation', ArrayField(models.CharField(max_length=100, blank=True, null=True))),
                ('entity', models.CharField(blank=True, max_length=20, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True, verbose_name='date registered')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
