# Generated by Django 3.0.7 on 2020-06-24 12:12

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('business_abbr', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('annual_sales_revenue', models.DecimalField(decimal_places=4, max_digits=19)),
                ('accounting_software', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, default='United States of America', max_length=100, null=True)),
                ('countries_of_operation', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=None)),
                ('entity', models.CharField(blank=True, max_length=20, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True, verbose_name='date registered')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
