# Generated by Django 3.0.7 on 2020-06-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20200614_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='sales_revenue',
        ),
        migrations.AddField(
            model_name='business',
            name='annual_sales_revenue',
            field=models.DecimalField(decimal_places=4, default=200.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='business',
            name='annual_sales_revenue_currency',
            field=models.DecimalField(decimal_places=4, default=200.0, max_digits=19)
        ),
        migrations.AlterField(
            model_name='business',
            name='business_abbr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
