# Generated by Django 3.0.7 on 2020-06-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20200614_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='country',
            field=models.CharField(blank=True, default='United States of America', max_length=100, null=True),
        ),
    ]
