# Generated by Django 3.0.7 on 2020-06-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_auto_20200615_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='country',
            field=models.CharField(blank=True, default='United States of America', max_length=100, null=True),
        ),
    ]
