# Generated by Django 3.0.7 on 2020-06-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20200615_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='annual_sales_revenue_currency',
        ),
        migrations.AlterField(
            model_name='business',
            name='annual_sales_revenue',
            field=models.DecimalField(decimal_places=4, default=200.0, max_digits=19),
            preserve_default=False,
        ),
    ]
