# Generated by Django 3.0.7 on 2020-06-15 12:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_auto_20200615_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='countries_of_operation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='business',
            name='country',
            field=models.CharField(blank=True, default='United States of America', max_length=100, null=True),
        ),
    ]
