version: '3'

services:
  rest_api: &rest_api
    build: .
    restart: on-failure
    env_file:
      - ./.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
      - celery_worker
  db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:alpine
  celery_worker:
    <<: *rest_api
    command: celery -A offline_business_analyzer worker --loglevel=info
    ports: []
    depends_on:
      - rabbitmq
      - db
  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
    depends_on:
      - rabbitmq
