# Generated by Django 3.0.7 on 2020-06-24 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.IntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'open'), ('CLOSED', 'closed')], default='open', max_length=10)),
                ('supplier', models.CharField(max_length=100)),
                ('unit_amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('total_transaction', models.DecimalField(decimal_places=4, max_digits=19)),
                ('transaction_date', models.DateField()),
                ('item', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit_amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('total_transaction', models.DecimalField(decimal_places=4, max_digits=19)),
                ('order_id', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('ACCEPTED', 'accepted'), ('REJECTED', 'rejected'), ('COMPLETED', 'completed')], default='pending', max_length=20)),
                ('transaction_date', models.DateField()),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='csv_file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='business.Business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('transaction_date', models.DateField()),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payments', to='transaction.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='transaction.Transaction'),
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=100)),
                ('transaction_date', models.DateField()),
                ('bill_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_payment', to='transaction.Bill')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='transaction.Transaction'),
        ),
    ]
