# Generated by Django 3.0.7 on 2020-07-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
