# Generated by Django 3.0.7 on 2020-06-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20200615_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='total_transaction_currency',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='unit_amount_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_transaction_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='unit_amount_currency',
        ),
    ]
