# Generated by Django 3.0.7 on 2020-07-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20200706_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='csv'),
        ),
    ]
