# Generated by Django 3.0.7 on 2020-06-15 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0004_auto_20200615_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bills',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='orders',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
