# Generated by Django 3.0.7 on 2020-06-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20200615_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='business',
        ),
    ]
