# Generated by Django 3.0.7 on 2020-07-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20200706_1357 2'),
        ('transaction', '0003_auto_20200706_1402 2'),
        ('transaction', '0004_auto_20200706_1638 2'),
        ('transaction', '0005_auto_20200706_1717 2'),
        ('transaction', '0005_auto_20200706_1717'),
    ]

    operations = [
    ]
