# Generated by Django 3.0.7 on 2020-06-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_remove_transaction_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='csv_file'),
        ),
    ]
