# Generated by Django 3.0.7 on 2020-06-23 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_auto_20200618_1708'),
        ('transaction', '0007_auto_20200615_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bills',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaction.Bill'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='business.Business'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='orders',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaction.Order'),
        ),
    ]
