# Generated by Django 3.0.7 on 2020-06-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20200623_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='item',
            field=models.CharField(default='bamboo', max_length=100),
            preserve_default=False,
        ),
    ]
