# Generated by Django 3.0.7 on 2020-06-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_bill_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='quantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
